-- ============================================================
-- seed_vocabulary_extended.sql
-- ~300 vocabulary words across A1–C1, organized by category
-- Run AFTER seed.sql (avoids duplicates from starter set)
-- ============================================================

INSERT INTO public.vocabulary_words
  (word_en, word_bg, phonetic, level, category, example_en, example_bg)
VALUES

-- ── A1 · Цветове (Colors) ─────────────────────────────────────────────────────
('red',    'червен',   '/red/',        'A1', 'Цветове', 'Her dress is red.',           'Роклята й е червена.'),
('blue',   'син',      '/bluː/',       'A1', 'Цветове', 'The sky is blue.',            'Небето е синьо.'),
('green',  'зелен',   '/ɡriːn/',      'A1', 'Цветове', 'Grass is green.',             'Тревата е зелена.'),
('yellow', 'жълт',    '/ˈjeloʊ/',     'A1', 'Цветове', 'The sun is yellow.',          'Слънцето е жълто.'),
('white',  'бял',     '/waɪt/',       'A1', 'Цветове', 'Snow is white.',              'Снегът е бял.'),
('black',  'черен',   '/blæk/',       'A1', 'Цветове', 'The cat is black.',           'Котката е черна.'),
('orange', 'оранжев', '/ˈɒrɪndʒ/',   'A1', 'Цветове', 'Oranges are orange.',         'Портокалите са оранжеви.'),
('purple', 'лилав',   '/ˈpɜːrpəl/',  'A1', 'Цветове', 'Violets are purple.',         'Теменугите са лилави.'),
('pink',   'розов',   '/pɪŋk/',       'A1', 'Цветове', 'The flowers are pink.',       'Цветята са розови.'),
('brown',  'кафяв',   '/braʊn/',      'A1', 'Цветове', 'The dog is brown.',           'Кучето е кафяво.'),
('grey',   'сив',     '/ɡreɪ/',       'A1', 'Цветове', 'The clouds are grey.',        'Облаците са сиви.'),

-- ── A1 · Тялото (Body) ───────────────────────────────────────────────────────
('head',   'глава',   '/hed/',        'A1', 'Тялото', 'My head hurts.',               'Боли ме главата.'),
('hand',   'ръка',    '/hænd/',       'A1', 'Тялото', 'Wash your hands.',             'Измий ръцете си.'),
('foot',   'крак',    '/fʊt/',        'A1', 'Тялото', 'My foot is cold.',             'Кракът ми е студен.'),
('eye',    'око',     '/aɪ/',         'A1', 'Тялото', 'She has blue eyes.',           'Тя има сини очи.'),
('ear',    'ухо',     '/ɪər/',        'A1', 'Тялото', 'I have pain in my ear.',       'Боли ме ухото.'),
('nose',   'нос',     '/noʊz/',       'A1', 'Тялото', 'His nose is red.',             'Носът му е червен.'),
('mouth',  'уста',    '/maʊθ/',       'A1', 'Тялото', 'Open your mouth.',             'Отвори устата си.'),
('arm',    'ръка (горна)', '/ɑːrm/', 'A1', 'Тялото', 'She broke her arm.',           'Тя счупи ръката си.'),
('leg',    'крак (долен)', '/leɡ/',  'A1', 'Тялото', 'He has long legs.',            'Той има дълги крака.'),
('back',   'гръб',    '/bæk/',        'A1', 'Тялото', 'My back is sore.',             'Гърбът ми ме боли.'),
('tooth',  'зъб',     '/tuːθ/',       'A1', 'Тялото', 'Brush your teeth twice a day.','Мий зъбите си два пъти на ден.'),
('hair',   'коса',    '/heər/',       'A1', 'Тялото', 'She has long hair.',           'Тя има дълга коса.'),

-- ── A1 · Храна и напитки (Food & Drink) ─────────────────────────────────────
('bread',   'хляб',    '/bred/',      'A1', 'Храна и напитки', 'I eat bread every morning.',   'Ям хляб всяка сутрин.'),
('milk',    'мляко',   '/mɪlk/',      'A1', 'Храна и напитки', 'Children drink milk.',          'Децата пият мляко.'),
('egg',     'яйце',    '/eɡ/',        'A1', 'Храна и напитки', 'I eat two eggs for breakfast.', 'Ям две яйца за закуска.'),
('apple',   'ябълка',  '/ˈæpəl/',     'A1', 'Храна и напитки', 'An apple a day is healthy.',   'Ябълка на ден е здравословно.'),
('banana',  'банан',   '/bəˈnɑːnə/', 'A1', 'Храна и напитки', 'Bananas are yellow.',           'Бананите са жълти.'),
('rice',    'ориз',    '/raɪs/',      'A1', 'Храна и напитки', 'We eat rice with vegetables.',  'Ядем ориз с зеленчуци.'),
('meat',    'месо',    '/miːt/',      'A1', 'Храна и напитки', 'He doesn''t eat meat.',          'Той не яде месо.'),
('fish',    'риба',    '/fɪʃ/',       'A1', 'Храна и напитки', 'Fish is healthy.',              'Рибата е полезна.'),
('chicken', 'пиле',    '/ˈtʃɪkɪn/',  'A1', 'Храна и напитки', 'I like chicken soup.',          'Харесвам пилешка супа.'),
('soup',    'супа',    '/suːp/',      'A1', 'Храна и напитки', 'This soup is hot.',             'Тази супа е гореща.'),
('cake',    'торта',   '/keɪk/',      'A1', 'Храна и напитки', 'She made a chocolate cake.',    'Тя направи шоколадова торта.'),
('coffee',  'кафе',    '/ˈkɒfi/',     'A1', 'Храна и напитки', 'I drink coffee every morning.', 'Пия кафе всяка сутрин.'),
('tea',     'чай',     '/tiː/',       'A1', 'Храна и напитки', 'Do you want tea or coffee?',   'Искаш ли чай или кафе?'),
('juice',   'сок',     '/dʒuːs/',     'A1', 'Храна и напитки', 'Orange juice is my favourite.', 'Портокаловият сок е любимият ми.'),
('sugar',   'захар',   '/ˈʃʊɡər/',   'A1', 'Храна и напитки', 'How much sugar do you want?',  'Колко захар искаш?'),
('butter',  'масло',   '/ˈbʌtər/',   'A1', 'Храна и напитки', 'Put butter on the bread.',      'Намажи хляба с масло.'),
('cheese',  'сирене',  '/tʃiːz/',     'A1', 'Храна и напитки', 'I love cheese.',                'Обичам сирене.'),
('tomato',  'домат',   '/təˈmeɪtoʊ/','A1', 'Храна и напитки', 'Tomatoes are red.',             'Доматите са червени.'),

-- ── A1 · Дрехи (Clothing) ────────────────────────────────────────────────────
('shirt',    'риза',    '/ʃɜːrt/',    'A1', 'Дрехи', 'He wears a white shirt.',     'Той носи бяла риза.'),
('trousers', 'панталон','/ˈtraʊzərz/','A1','Дрехи', 'These trousers are too big.', 'Тези панталони са твърде широки.'),
('dress',    'рокля',   '/dres/',     'A1', 'Дрехи', 'She wears a red dress.',      'Тя носи червена рокля.'),
('shoes',    'обувки',  '/ʃuːz/',     'A1', 'Дрехи', 'My shoes are too tight.',     'Обувките ми са твърде тесни.'),
('jacket',   'яке',     '/ˈdʒækɪt/', 'A1', 'Дрехи', 'Take your jacket — it''s cold.','Вземи якето — студено е.'),
('hat',      'шапка',   '/hæt/',      'A1', 'Дрехи', 'She wears a big hat.',        'Тя носи голяма шапка.'),
('coat',     'палто',   '/koʊt/',     'A1', 'Дрехи', 'I need a warm coat.',         'Трябва ми топло палто.'),
('socks',    'чорапи',  '/sɒks/',     'A1', 'Дрехи', 'Put your socks on.',          'Сложи чорапите си.'),
('bag',      'чанта',   '/bæɡ/',      'A1', 'Дрехи', 'Her bag is heavy.',           'Чантата й е тежка.'),
('glasses',  'очила',   '/ˈɡlɑːsɪz/','A1', 'Дрехи', 'I need glasses to read.',     'Трябват ми очила, за да чета.'),

-- ── A1 · Животни (Animals) ───────────────────────────────────────────────────
('dog',      'куче',   '/dɒɡ/',      'A1', 'Животни', 'My dog is very friendly.',    'Кучето ми е много дружелюбно.'),
('cat',      'котка',  '/kæt/',      'A1', 'Животни', 'The cat sleeps all day.',     'Котката спи цял ден.'),
('bird',     'птица',  '/bɜːrd/',    'A1', 'Животни', 'I hear a bird singing.',      'Чувам птица да пее.'),
('horse',    'кон',    '/hɔːrs/',    'A1', 'Животни', 'She rides a horse.',          'Тя яхва кон.'),
('cow',      'крава',  '/kaʊ/',      'A1', 'Животни', 'Cows give us milk.',          'Кравите ни дават мляко.'),
('sheep',    'овца',   '/ʃiːp/',     'A1', 'Животни', 'There are sheep on the hill.','На хълма има овце.'),
('fish',     'риба',   '/fɪʃ/',      'A1', 'Животни', 'There are fish in the river.','В реката има риби.'),
('rabbit',   'заек',   '/ˈræbɪt/',  'A1', 'Животни', 'The rabbit is white.',        'Заекът е бял.'),
('bear',     'мечка',  '/beər/',     'A1', 'Животни', 'Bears live in forests.',      'Мечките живеят в гори.'),
('lion',     'лъв',    '/ˈlaɪən/',  'A1', 'Животни', 'The lion is the king.',       'Лъвът е царят.'),
('elephant', 'слон',   '/ˈelɪfənt/','A1', 'Животни', 'Elephants have long trunks.',  'Слоновете имат дълги хоботи.'),

-- ── A1 · Ежедневни глаголи (Daily Verbs) ────────────────────────────────────
('eat',     'ям',        '/iːt/',     'A1', 'Глаголи', 'I eat breakfast at 8.',       'Закусвам в 8 часа.'),
('drink',   'пия',       '/drɪŋk/',  'A1', 'Глаголи', 'Drink more water.',            'Пий повече вода.'),
('sleep',   'спя',       '/sliːp/',  'A1', 'Глаголи', 'I sleep 8 hours a night.',    'Спя 8 часа на нощ.'),
('walk',    'ходя пеша', '/wɔːk/',   'A1', 'Глаголи', 'I walk to school.',            'Ходя пеша до училище.'),
('run',     'бягам',     '/rʌn/',    'A1', 'Глаголи', 'She runs every morning.',     'Тя бяга всяка сутрин.'),
('read',    'чета',      '/riːd/',   'A1', 'Глаголи', 'I read before bed.',           'Чета преди сън.'),
('write',   'пиша',      '/raɪt/',   'A1', 'Глаголи', 'Write your name here.',        'Напиши името си тук.'),
('speak',   'говоря',    '/spiːk/',  'A1', 'Глаголи', 'Do you speak English?',        'Говориш ли английски?'),
('listen',  'слушам',    '/ˈlɪsən/', 'A1', 'Глаголи', 'Listen to the teacher.',       'Слушай учителя.'),
('watch',   'гледам',    '/wɒtʃ/',   'A1', 'Глаголи', 'I watch TV in the evening.',   'Гледам телевизия вечер.'),
('play',    'играя',     '/pleɪ/',   'A1', 'Глаголи', 'Children play in the park.',  'Децата играят в парка.'),
('work',    'работя',    '/wɜːrk/',  'A1', 'Глаголи', 'She works in a hospital.',    'Тя работи в болница.'),
('live',    'живея',     '/lɪv/',    'A1', 'Глаголи', 'I live in Sofia.',             'Живея в София.'),
('love',    'обичам',    '/lʌv/',    'A1', 'Глаголи', 'I love my family.',            'Обичам семейството си.'),
('like',    'харесвам',  '/laɪk/',   'A1', 'Глаголи', 'I like ice cream.',            'Харесвам сладолед.'),
('need',    'трябва ми', '/niːd/',   'A1', 'Глаголи', 'I need your help.',            'Нуждая се от помощта ти.'),
('want',    'искам',     '/wɒnt/',   'A1', 'Глаголи', 'I want a coffee, please.',     'Искам кафе, моля.'),
('buy',     'купувам',   '/baɪ/',    'A1', 'Глаголи', 'I buy milk every day.',        'Купувам мляко всеки ден.'),
('open',    'отварям',   '/ˈoʊpən/', 'A1', 'Глаголи', 'Please open the window.',      'Моля отвори прозореца.'),
('close',   'затварям',  '/kloʊz/',  'A1', 'Глаголи', 'Close the door, please.',      'Затвори вратата, моля.'),

-- ── A1 · Места (Places) ──────────────────────────────────────────────────────
('school',    'училище',  '/skuːl/',      'A1', 'Места', 'She goes to school at 8.', 'Тя отива на училище в 8.'),
('hospital',  'болница',  '/ˈhɒspɪtəl/', 'A1', 'Места', 'He is in hospital.',        'Той е в болница.'),
('park',      'парк',     '/pɑːrk/',      'A1', 'Места', 'We walk in the park.',      'Разхождаме се в парка.'),
('shop',      'магазин',  '/ʃɒp/',        'A1', 'Места', 'I buy food at the shop.',   'Купувам храна в магазина.'),
('restaurant','ресторант','/ˈrestrɒnt/',  'A1', 'Места', 'Let''s eat at a restaurant.','Хайде да ядем в ресторант.'),
('bank',      'банка',    '/bæŋk/',       'A1', 'Места', 'The bank opens at 9.',      'Банката отваря в 9.'),
('library',   'библиотека','/ˈlaɪbrəri/', 'A1', 'Места', 'I study in the library.',   'Уча в библиотеката.'),
('station',   'гара',     '/ˈsteɪʃən/',   'A1', 'Места', 'The station is nearby.',    'Гарата е наблизо.'),
('church',    'църква',   '/tʃɜːrtʃ/',    'A1', 'Места', 'The church is very old.',   'Църквата е много стара.'),
('market',    'пазар',    '/ˈmɑːrkɪt/',   'A1', 'Места', 'We buy vegetables at the market.','Купуваме зеленчуци от пазара.'),
('cinema',    'кино',     '/ˈsɪnəmə/',    'A1', 'Места', 'Let''s go to the cinema.',   'Хайде да отидем на кино.'),
('gym',       'фитнес',   '/dʒɪm/',       'A1', 'Места', 'I go to the gym three times a week.','Ходя на фитнес три пъти седмично.'),

-- ── A1 · Прилагателни (Adjectives) ──────────────────────────────────────────
('big',    'голям',    '/bɪɡ/',       'A1', 'Прилагателни', 'That is a big dog.',         'Това е голямо куче.'),
('small',  'малък',    '/smɔːl/',     'A1', 'Прилагателни', 'She has a small car.',       'Тя има малка кола.'),
('tall',   'висок',    '/tɔːl/',      'A1', 'Прилагателни', 'He is very tall.',           'Той е много висок.'),
('short',  'нисък',    '/ʃɔːrt/',     'A1', 'Прилагателни', 'She is short.',              'Тя е ниска.'),
('long',   'дълъг',    '/lɒŋ/',       'A1', 'Прилагателни', 'It''s a long road.',          'Това е дълъг път.'),
('hot',    'горещ',    '/hɒt/',       'A1', 'Прилагателни', 'The coffee is hot.',         'Кафето е горещо.'),
('cold',   'студен',   '/koʊld/',     'A1', 'Прилагателни', 'It''s cold today.',           'Днес е студено.'),
('new',    'нов',      '/njuː/',      'A1', 'Прилагателни', 'I have a new phone.',        'Имам нов телефон.'),
('old',    'стар',     '/oʊld/',      'A1', 'Прилагателни', 'This is an old book.',       'Това е стара книга.'),
('good',   'добър',    '/ɡʊd/',       'A1', 'Прилагателни', 'This food is good.',         'Тази храна е добра.'),
('bad',    'лош',      '/bæd/',       'A1', 'Прилагателни', 'The weather is bad.',        'Времето е лошо.'),
('happy',  'щастлив',  '/ˈhæpi/',     'A1', 'Прилагателни', 'She looks happy.',           'Изглежда щастлива.'),
('sad',    'тъжен',    '/sæd/',       'A1', 'Прилагателни', 'Why are you sad?',           'Защо си тъжен?'),
('tired',  'уморен',   '/ˈtaɪərd/',  'A1', 'Прилагателни', 'I''m very tired today.',      'Много съм уморен днес.'),
('hungry', 'гладен',   '/ˈhʌŋɡri/',  'A1', 'Прилагателни', 'I''m hungry — let''s eat.',   'Гладен съм — хайде да ядем.'),
('full',   'сит',      '/fʊl/',       'A1', 'Прилагателни', 'I''m full, thank you.',       'Сит съм, благодаря.'),
('fast',   'бърз',     '/fæst/',      'A1', 'Прилагателни', 'He is a fast runner.',       'Той е бърз бегач.'),
('slow',   'бавен',    '/sloʊ/',      'A1', 'Прилагателни', 'This train is slow.',        'Този влак е бавен.'),
('free',   'свободен / безплатен', '/friː/', 'A1', 'Прилагателни', 'The app is free.', 'Приложението е безплатно.'),
('busy',   'зает',     '/ˈbɪzi/',     'A1', 'Прилагателни', 'I''m busy right now.',        'Сега съм зает.'),

-- ── A2 · Пътуване (Travel) ────────────────────────────────────────────────────
('passport',   'паспорт',     '/ˈpɑːspɔːrt/', 'A2', 'Пътуване', 'Don''t forget your passport.','Не забравяй паспорта си.'),
('luggage',    'багаж',       '/ˈlʌɡɪdʒ/',   'A2', 'Пътуване', 'My luggage is too heavy.',  'Багажът ми е твърде тежък.'),
('flight',     'полет',       '/flaɪt/',      'A2', 'Пътуване', 'Our flight is at 7 a.m.',   'Полетът ни е в 7 сутринта.'),
('departure',  'заминаване',  '/dɪˈpɑːrtʃər/','A2','Пътуване', 'Check the departure time.', 'Провери времето на заминаване.'),
('arrival',    'пристигане',  '/əˈraɪvəl/',   'A2', 'Пътуване', 'We waited for her arrival.','Чакахме нейното пристигане.'),
('platform',   'перон',       '/ˈplætfɔːrm/', 'A2', 'Пътуване', 'The train leaves from platform 3.','Влакът тръгва от перон 3.'),
('taxi',       'такси',       '/ˈtæksi/',     'A2', 'Пътуване', 'Let''s take a taxi.',        'Хайде да вземем такси.'),
('bus',        'автобус',     '/bʌs/',        'A2', 'Пътуване', 'The bus arrives at 9.',     'Автобусът пристига в 9.'),
('train',      'влак',        '/treɪn/',      'A2', 'Пътуване', 'The train to Sofia is fast.','Влакът за София е бърз.'),
('bicycle',    'велосипед',   '/ˈbaɪsɪkəl/', 'A2', 'Пътуване', 'I ride my bicycle to work.','Карам велосипед до работа.'),
('car',        'кола',        '/kɑːr/',       'A2', 'Пътуване', 'She drives her car to work.','Тя кара кола до работа.'),
('direction',  'посока',      '/daɪˈrekʃən/','A2', 'Пътуване', 'Turn left at the next direction.','Завий наляво на следващото кръстовище.'),
('north',      'север',       '/nɔːrθ/',      'A2', 'Пътуване', 'The city is to the north.', 'Градът е на север.'),
('south',      'юг',          '/saʊθ/',       'A2', 'Пътуване', 'We drove south.',           'Карахме на юг.'),
('east',       'изток',       '/iːst/',       'A2', 'Пътуване', 'The sun rises in the east.','Слънцето изгрява на изток.'),
('west',       'запад',       '/west/',       'A2', 'Пътуване', 'The sun sets in the west.', 'Слънцето залязва на запад.'),

-- ── A2 · Домът (Home) ────────────────────────────────────────────────────────
('bedroom',   'спалня',    '/ˈbedruːm/',    'A2', 'Домът', 'The bedroom is upstairs.',   'Спалнята е горе.'),
('kitchen',   'кухня',     '/ˈkɪtʃɪn/',    'A2', 'Домът', 'I cook in the kitchen.',     'Готвя в кухнята.'),
('bathroom',  'баня',      '/ˈbɑːθruːm/',  'A2', 'Домът', 'The bathroom is clean.',     'Банята е чиста.'),
('living room','хол',      NULL,            'A2', 'Домът', 'We watch TV in the living room.','Гледаме телевизия в хола.'),
('garden',    'градина',   '/ˈɡɑːrdən/',   'A2', 'Домът', 'She grows tomatoes in her garden.','Тя отглежда домати в градината си.'),
('window',    'прозорец',  '/ˈwɪndoʊ/',    'A2', 'Домът', 'Open the window, please.',   'Моля, отвори прозореца.'),
('door',      'врата',     '/dɔːr/',        'A2', 'Домът', 'Please close the door.',     'Моля, затвори вратата.'),
('floor',     'под',       '/flɔːr/',       'A2', 'Домът', 'The floor is cold.',         'Подът е студен.'),
('ceiling',   'таван',     '/ˈsiːlɪŋ/',    'A2', 'Домът', 'The ceiling is very high.',  'Таванът е много висок.'),
('furniture', 'мебели',    '/ˈfɜːrnɪtʃər/','A2','Домът', 'Buy new furniture for the flat.','Купи нови мебели за апартамента.'),
('table',     'маса',      '/ˈteɪbəl/',    'A2', 'Домът', 'Dinner is on the table.',    'Вечерята е на масата.'),
('chair',     'стол',      '/tʃeər/',       'A2', 'Домът', 'Sit on this chair.',         'Седни на този стол.'),
('bed',       'легло',     '/bed/',         'A2', 'Домът', 'I went to bed early.',       'Легнах рано.'),
('lamp',      'лампа',     '/læmp/',        'A2', 'Домът', 'Turn on the lamp.',          'Пусни лампата.'),
('key',       'ключ',      '/kiː/',         'A2', 'Домът', 'I can''t find my key.',       'Не мога да намеря ключа си.'),

-- ── A2 · Времето (Weather) ────────────────────────────────────────────────────
('sunny',    'слънчево',   '/ˈsʌni/',      'A2', 'Времето', 'It''s sunny today.',           'Днес е слънчево.'),
('rainy',    'дъждовно',   '/ˈreɪni/',     'A2', 'Времето', 'It''s rainy outside.',         'Навън е дъждовно.'),
('cloudy',   'облачно',    '/ˈklaʊdi/',    'A2', 'Времето', 'The sky is cloudy.',           'Небето е облачно.'),
('windy',    'ветровито',  '/ˈwɪndi/',     'A2', 'Времето', 'It''s very windy today.',      'Днес е много ветровито.'),
('snow',     'сняг',       '/snoʊ/',       'A2', 'Времето', 'The snow is beautiful.',       'Снегът е красив.'),
('rain',     'дъжд',       '/reɪn/',       'A2', 'Времето', 'I love the sound of rain.',    'Обичам звука на дъжда.'),
('storm',    'буря',       '/stɔːrm/',     'A2', 'Времето', 'There is a storm coming.',     'Идва буря.'),
('fog',      'мъгла',      '/fɒɡ/',        'A2', 'Времето', 'Drive carefully in the fog.',  'Карай внимателно в мъглата.'),
('wind',     'вятър',      '/wɪnd/',       'A2', 'Времето', 'A cold wind is blowing.',      'Духа студен вятър.'),
('sun',      'слънце',     '/sʌn/',        'A2', 'Времето', 'The sun is shining.',          'Слънцето грее.'),
('temperature','температура','/ˌtempəˈreɪtʃər/','A2','Времето','The temperature is low.','Температурата е ниска.'),

-- ── A2 · Емоции (Emotions) ────────────────────────────────────────────────────
('excited',      'развълнуван', '/ɪkˈsaɪtɪd/', 'A2', 'Емоции', 'I''m excited about the trip.','Развълнуван съм от пътуването.'),
('nervous',      'нервен',      '/ˈnɜːrvəs/',  'A2', 'Емоции', 'She feels nervous before the exam.','Тя се чувства нервна преди изпита.'),
('angry',        'ядосан',      '/ˈæŋɡri/',    'A2', 'Емоции', 'He is angry with me.',       'Той е ядосан с мен.'),
('surprised',    'изненадан',   '/sərˈpraɪzd/','A2', 'Емоции', 'She was surprised by the news.','Тя беше изненадана от новините.'),
('bored',        'скучен',      '/bɔːrd/',      'A2', 'Емоции', 'I''m bored — let''s do something.','Скучно ми е — хайде да правим нещо.'),
('proud',        'горд',        '/praʊd/',      'A2', 'Емоции', 'She is proud of her son.',   'Тя е горда от сина си.'),
('worried',      'притеснен',   '/ˈwʌrid/',     'A2', 'Емоции', 'I''m worried about him.',    'Притеснявам се за него.'),
('disappointed', 'разочарован', '/ˌdɪsəˈpɔɪntɪd/','A2','Емоции','He was disappointed.',     'Той беше разочарован.'),
('afraid',       'уплашен',     '/əˈfreɪd/',    'A2', 'Емоции', 'She is afraid of spiders.',  'Тя се страхува от паяци.'),
('lonely',       'самотен',     '/ˈloʊnli/',    'A2', 'Емоции', 'He feels lonely.',           'Той се чувства самотен.'),
('embarrassed',  'смутен',      '/ɪmˈbærəst/',  'A2', 'Емоции', 'She was embarrassed.',       'Тя беше смутена.'),

-- ── B1 · Работа (Work) ────────────────────────────────────────────────────────
('career',    'кариера',    '/kəˈrɪər/',     'B1', 'Работа', 'She has a good career.',     'Тя има добра кариера.'),
('salary',    'заплата',    '/ˈsæləri/',     'B1', 'Работа', 'The salary is not enough.',  'Заплатата не е достатъчна.'),
('interview', 'интервю',    '/ˈɪntərvjuː/', 'B1', 'Работа', 'I have an interview tomorrow.','Утре имам интервю.'),
('promotion', 'повишение',  '/prəˈmoʊʃən/', 'B1', 'Работа', 'She got a promotion.',       'Тя получи повишение.'),
('colleague', 'колега',     '/ˈkɒliːɡ/',    'B1', 'Работа', 'He is my colleague.',        'Той е мой колега.'),
('boss',      'шеф',        '/bɒs/',        'B1', 'Работа', 'My boss is very strict.',    'Шефът ми е много строг.'),
('office',    'офис',       '/ˈɒfɪs/',      'B1', 'Работа', 'I work in a big office.',    'Работя в голям офис.'),
('deadline',  'краен срок', '/ˈdedlaɪn/',   'B1', 'Работа', 'We have a tight deadline.',  'Имаме стегнат краен срок.'),
('report',    'доклад',     '/rɪˈpɔːrt/',   'B1', 'Работа', 'Submit the report by Friday.','Предай доклада до петък.'),
('meeting',   'среща',      '/ˈmiːtɪŋ/',    'B1', 'Работа', 'The meeting starts at 10.',  'Срещата започва в 10.'),
('resign',    'подавам оставка','/rɪˈzaɪn/', 'B1','Работа', 'He decided to resign.',      'Той реши да подаде оставка.'),
('hire',      'наемам',     '/haɪər/',       'B1', 'Работа', 'They hired a new manager.',  'Те наеха нов мениджър.'),
('retire',    'пенсионирам се','/rɪˈtaɪər/', 'B1','Работа', 'She retired at 65.',         'Тя се пенсионира на 65.'),
('skill',     'умение',     '/skɪl/',        'B1', 'Работа', 'Good communication is a key skill.','Добрата комуникация е ключово умение.'),
('task',      'задача',     '/tɑːsk/',       'B1', 'Работа', 'Complete the task by noon.', 'Изпълни задачата до обяд.'),

-- ── B1 · Здраве (Health) ──────────────────────────────────────────────────────
('headache',  'главоболие',  '/ˈhedeɪk/',   'B1', 'Здраве', 'I have a terrible headache.','Имам ужасно главоболие.'),
('fever',     'треска',      '/ˈfiːvər/',   'B1', 'Здраве', 'She has a high fever.',      'Тя има висока треска.'),
('cough',     'кашлица',     '/kɒf/',       'B1', 'Здраве', 'He has a bad cough.',        'Той има лоша кашлица.'),
('medicine',  'лекарство',   '/ˈmedɪsɪn/', 'B1', 'Здраве', 'Take your medicine.',        'Вземи лекарството си.'),
('pill',      'хапче',       '/pɪl/',       'B1', 'Здраве', 'Take one pill a day.',       'Вземай по едно хапче на ден.'),
('doctor',    'лекар',       '/ˈdɒktər/',  'B1', 'Здраве', 'I need to see a doctor.',    'Трябва да отида при лекар.'),
('appointment','час (при лекар)','/əˈpɔɪntmənt/','B1','Здраве','I have a doctor''s appointment.','Имам час при лекар.'),
('surgery',   'операция',    '/ˈsɜːrdʒəri/','B1','Здраве', 'She had heart surgery.',     'Тя имаше сърдечна операция.'),
('disease',   'болест',      '/dɪˈziːz/',   'B1', 'Здраве', 'This disease spreads fast.', 'Тази болест се разпространява бързо.'),
('symptom',   'симптом',     '/ˈsɪmptəm/',  'B1', 'Здраве', 'What are the symptoms?',    'Какви са симптомите?'),
('recovery',  'оздравяване', '/rɪˈkʌvəri/', 'B1', 'Здраве', 'His recovery is slow.',     'Неговото оздравяване е бавно.'),
('allergy',   'алергия',     '/ˈælədʒi/',   'B1', 'Здраве', 'She has a food allergy.',   'Тя има хранителна алергия.'),
('exercise',  'упражнение',  '/ˈeksərsaɪz/','B1','Здраве', 'Regular exercise is healthy.','Редовното упражнение е полезно.'),
('diet',      'диета',       '/ˈdaɪət/',    'B1', 'Здраве', 'She is on a strict diet.',  'Тя е на строга диета.'),
('stress',    'стрес',       '/stres/',      'B1', 'Здраве', 'Stress can cause illness.',  'Стресът може да причини болест.'),

-- ── B1 · Образование (Education) ─────────────────────────────────────────────
('university','университет', '/ˌjuːnɪˈvɜːrsɪti/','B1','Образование','She studies at university.','Тя учи в университет.'),
('degree',    'степен',     '/dɪˈɡriː/',    'B1', 'Образование', 'He has a master''s degree.','Той има магистърска степен.'),
('lecture',   'лекция',     '/ˈlektʃər/',   'B1', 'Образование', 'The lecture starts at 9.', 'Лекцията започва в 9.'),
('essay',     'есе',        '/ˈeseɪ/',      'B1', 'Образование', 'Write a 500-word essay.', 'Напиши есе от 500 думи.'),
('exam',      'изпит',      '/ɪɡˈzæm/',    'B1', 'Образование', 'I have an exam tomorrow.','Утре имам изпит.'),
('grade',     'оценка',     '/ɡreɪd/',      'B1', 'Образование', 'She got a good grade.',   'Тя получи добра оценка.'),
('subject',   'предмет',    '/ˈsʌbdʒɪkt/',  'B1', 'Образование', 'What is your favourite subject?','Кой е любимият ти предмет?'),
('homework',  'домашна работа','/ˈhoʊmwɜːrk/','B1','Образование','Do your homework first.','Първо си направи домашното.'),
('scholarship','стипендия',  '/ˈskɒlərʃɪp/','B1','Образование','She won a scholarship.',   'Тя спечели стипендия.'),
('professor', 'професор',   '/prəˈfesər/',  'B1', 'Образование', 'The professor is strict.','Професорът е строг.'),
('knowledge', 'знание',     '/ˈnɒlɪdʒ/',   'B1', 'Образование', 'Knowledge is power.',     'Знанието е сила.'),

-- ── B1 · Природа (Nature) ────────────────────────────────────────────────────
('mountain',  'планина',   '/ˈmaʊntɪn/',  'B1', 'Природа', 'We climbed the mountain.',  'Изкачихме планината.'),
('river',     'река',      '/ˈrɪvər/',    'B1', 'Природа', 'The river is very long.',   'Реката е много дълга.'),
('forest',    'гора',      '/ˈfɒrɪst/',   'B1', 'Природа', 'The forest is beautiful.',  'Гората е красива.'),
('ocean',     'океан',     '/ˈoʊʃən/',    'B1', 'Природа', 'The ocean is vast.',        'Океанът е огромен.'),
('island',    'остров',    '/ˈaɪlənd/',   'B1', 'Природа', 'She lives on an island.',   'Тя живее на остров.'),
('desert',    'пустиня',   '/ˈdezərt/',   'B1', 'Природа', 'The desert is very hot.',   'Пустинята е много гореща.'),
('valley',    'долина',    '/ˈvæli/',     'B1', 'Природа', 'The valley is green.',      'Долината е зелена.'),
('lake',      'езеро',     '/leɪk/',      'B1', 'Природа', 'We swim in the lake.',      'Плуваме в езерото.'),
('coast',     'бряг',      '/koʊst/',     'B1', 'Природа', 'We walked along the coast.','Вървяхме по брега.'),
('cliff',     'скала',     '/klɪf/',      'B1', 'Природа', 'The cliff is very steep.',  'Скалата е много стръмна.'),

-- ── B2 · Характер (Personality) ──────────────────────────────────────────────
('confident',  'уверен',     '/ˈkɒnfɪdənt/', 'B2', 'Характер', 'She is very confident.',  'Тя е много уверена.'),
('determined', 'решителен',  '/dɪˈtɜːrmɪnd/','B2', 'Характер', 'He is determined to win.','Той е решен да победи.'),
('patient',    'търпелив',   '/ˈpeɪʃənt/',   'B2', 'Характер', 'Be patient — it takes time.','Бъди търпелив — нужно е време.'),
('honest',     'честен',     '/ˈɒnɪst/',     'B2', 'Характер', 'He is always honest.',    'Той е винаги честен.'),
('generous',   'щедър',      '/ˈdʒenərəs/',  'B2', 'Характер', 'She is very generous.',   'Тя е много щедра.'),
('stubborn',   'упорит/инат','/ˈstʌbərn/',   'B2', 'Характер', 'He is very stubborn.',    'Той е много инат.'),
('reliable',   'надежден',   '/rɪˈlaɪəbəl/', 'B2', 'Характер', 'She is a reliable person.','Тя е надежден човек.'),
('sensitive',  'чувствителен','/ˈsensɪtɪv/', 'B2', 'Характер', 'He is very sensitive.',   'Той е много чувствителен.'),
('arrogant',   'арогантен',  '/ˈærəɡənt/',   'B2', 'Характер', 'Don''t be arrogant.',      'Не бъди арогантен.'),
('humble',     'скромен',    '/ˈhʌmbəl/',    'B2', 'Характер', 'She is humble and kind.',  'Тя е скромна и мила.'),
('loyal',      'лоялен',     '/ˈlɔɪəl/',     'B2', 'Характер', 'He is a loyal friend.',   'Той е верен приятел.'),
('witty',      'остроумен',  '/ˈwɪti/',      'B2', 'Характер', 'She is very witty.',       'Тя е много остроумна.'),

-- ── B2 · Общество (Society) ──────────────────────────────────────────────────
('democracy',  'демокрация',  '/dɪˈmɒkrəsi/', 'B2', 'Общество', 'Democracy needs active citizens.','Демокрацията се нуждае от активни граждани.'),
('freedom',    'свобода',     '/ˈfriːdəm/',   'B2', 'Общество', 'Freedom of speech is important.','Свободата на словото е важна.'),
('justice',    'справедливост','/ˈdʒʌstɪs/',  'B2', 'Общество', 'We fight for justice.',   'Борим се за справедливост.'),
('poverty',    'бедност',     '/ˈpɒvəti/',    'B2', 'Общество', 'Poverty is a global issue.','Бедността е глобален проблем.'),
('equality',   'равенство',   '/ɪˈkwɒlɪti/',  'B2', 'Общество', 'We believe in equality.', 'Вярваме в равенството.'),
('culture',    'култура',     '/ˈkʌltʃər/',   'B2', 'Общество', 'Every country has its culture.','Всяка страна има своя култура.'),
('tradition',  'традиция',    '/trəˈdɪʃən/',  'B2', 'Общество', 'This is an old tradition.','Това е стара традиция.'),
('community',  'общност',     '/kəˈmjuːnɪti/','B2','Общество', 'She works for the community.','Тя работи за общността.'),
('minority',   'малцинство',  '/maɪˈnɒrɪti/', 'B2', 'Общество', 'Protect minority rights.', 'Защитавай правата на малцинствата.'),
('protest',    'протест',     '/ˈproʊtest/',   'B2', 'Общество', 'There was a large protest.','Имаше голям протест.'),

-- ── B2 · Технологии (Technology) ─────────────────────────────────────────────
('artificial intelligence','изкуствен интелект',NULL,'B2','Технологии','AI is changing the world.','ИИ промени света.'),
('algorithm',  'алгоритъм',   '/ˈælɡərɪðəm/','B2','Технологии', 'This algorithm is efficient.','Този алгоритъм е ефективен.'),
('data',       'данни',       '/ˈdeɪtə/',     'B2', 'Технологии', 'We need more data.',       'Нуждаем се от повече данни.'),
('network',    'мрежа',       '/ˈnetwɜːrk/',  'B2', 'Технологии', 'The network is slow.',     'Мрежата е бавна.'),
('password',   'парола',      '/ˈpæswɜːrd/',  'B2', 'Технологии', 'Don''t share your password.','Не споделяй паролата си.'),
('update',     'обновяване',  '/ˈʌpdeɪt/',    'B2', 'Технологии', 'Install the latest update.','Инсталирай последното обновяване.'),
('download',   'изтегляне',   '/ˈdaʊnloʊd/',  'B2', 'Технологии', 'Download the app for free.','Изтегли приложението безплатно.'),
('upload',     'качване',     '/ˈʌploʊd/',    'B2', 'Технологии', 'Upload your documents.',   'Качи документите си.'),
('cloud',      'облак (компютърен)','/klaʊd/', 'B2','Технологии', 'Save it in the cloud.',    'Запази го в облака.'),
('cybersecurity','киберсигурност',NULL,        'B2', 'Технологии', 'Cybersecurity is crucial.','Киберсигурността е от решаващо значение.'),

-- ── C1 · Академичен речник (Academic) ────────────────────────────────────────
('hypothesis',  'хипотеза',    '/haɪˈpɒθɪsɪs/','C1','Академичен', 'The hypothesis was proven.','Хипотезата беше доказана.'),
('phenomenon',  'феномен',     '/fɪˈnɒmɪnən/', 'C1', 'Академичен', 'This is a natural phenomenon.','Това е природен феномен.'),
('paradigm',    'парадигма',   '/ˈpærədaɪm/',  'C1', 'Академичен', 'A new paradigm is emerging.','Появява се нова парадигма.'),
('implication', 'последствие', '/ˌɪmplɪˈkeɪʃən/','C1','Академичен','What are the implications?','Какви са последствията?'),
('correlation', 'корелация',   '/ˌkɒrəˈleɪʃən/','C1','Академичен','There is a correlation here.','Тук има корелация.'),
('ambiguous',   'двусмислен',  '/æmˈbɪɡjuəs/', 'C1', 'Академичен', 'The statement is ambiguous.','Изявлението е двусмислено.'),
('analogous',   'аналогичен',  '/əˈnæləɡəs/',  'C1', 'Академичен', 'These cases are analogous.','Тези случаи са аналогични.'),
('critique',    'критика',     '/krɪˈtiːk/',   'C1', 'Академичен', 'Write a literary critique.','Напиши литературна критика.'),
('derive',      'извличам',    '/dɪˈraɪv/',    'C1', 'Академичен', 'Derive a conclusion from data.','Извлечи заключение от данните.'),
('elaborate',   'разрабoтвам', '/ɪˈlæbəreɪt/', 'C1', 'Академичен', 'Please elaborate on that point.','Моля, разработи тази точка.'),
('inherent',    'присъщ',      '/ɪnˈhɪərənt/', 'C1', 'Академичен', 'There is inherent risk here.','Тук има присъщ риск.'),
('leverage',    'използвам',   '/ˈlevərɪdʒ/',  'C1', 'Академичен', 'Leverage your strengths.',  'Използвай силните си страни.'),
('nonetheless', 'въпреки това', '/ˌnʌnðəˈles/', 'C1','Академичен', 'It is hard; nonetheless, try.','Трудно е; въпреки това опитай.'),
('perceive',    'възприемам',  '/pərˈsiːv/',   'C1', 'Академичен', 'How do you perceive this?', 'Как го възприемаш?'),
('prevalent',   'разпространен','/ˈprevələnt/', 'C1','Академичен', 'This opinion is prevalent.','Това мнение е широко разпространено.'),
('scrutiny',    'щателна проверка','/ˈskruːtɪni/','C1','Академичен','Under close scrutiny.',   'При внимателна проверка.'),
('sustain',     'поддържам',   '/səˈsteɪn/',   'C1', 'Академичен', 'Sustain a healthy lifestyle.','Поддържай здравословен начин на живот.'),
('underlying',  'основен/скрит','/ˌʌndərˈlaɪɪŋ/','C1','Академичен','What are the underlying causes?','Какви са скритите причини?'),

-- ── C1 · Характер и поведение (Character C1) ─────────────────────────────────
('audacious',   'дързък',      '/ɔːˈdeɪʃəs/',  'C1', 'Характер', 'An audacious plan.',       'Дързък план.'),
('frugal',      'пестелив',    '/ˈfruːɡəl/',   'C1', 'Характер', 'She lives a frugal life.', 'Тя живее пестеливо.'),
('impeccable',  'безупречен',  '/ɪmˈpekəbəl/', 'C1', 'Характер', 'Her work is impeccable.',  'Работата й е безупречна.'),
('tenacious',   'упорит/жилав','/tɪˈneɪʃəs/',  'C1', 'Характер', 'He is a tenacious worker.','Той е жилав работник.'),
('wary',        'предпазлив',  '/ˈweəri/',     'C1', 'Характер', 'Be wary of strangers.',    'Бъди предпазлив с непознати.'),
('candid',      'открит/искрен','/ˈkændɪd/',   'C1', 'Характер', 'She gave a candid answer.','Тя даде откровен отговор.'),
('compassionate','съчувствен', '/kəmˈpæʃənɪt/','C1','Характер', 'He is compassionate.',     'Той е съчувствен.'),
('diligent',    'прилежен',    '/ˈdɪlɪdʒənt/', 'C1', 'Характер', 'She is a diligent student.','Тя е прилежна студентка.');
