-- ============================================================
-- seed_vocabulary_v2.sql — ~200 words filling A2–B2 gaps
-- New categories: Shopping, Relationships, Leisure, Restaurant,
-- Time Expressions (A2); Finance, Sport, Environment, Tech (B1);
-- Media & News, Describing (B2)
-- Run AFTER seed_vocabulary_extended.sql
-- ============================================================

INSERT INTO public.vocabulary_words
  (word_en, word_bg, phonetic, level, category, example_en, example_bg)
VALUES

-- ── A2 · Пазаруване (Shopping) ───────────────────────────────────────────────
('receipt',       'касова бележка', '/rɪˈsiːt/',      'A2', 'Пазаруване', 'Keep your receipt.',                   'Пази касовата бележка.'),
('discount',      'отстъпка',       '/ˈdɪskaʊnt/',    'A2', 'Пазаруване', 'I got a 20% discount.',               'Получих 20% отстъпка.'),
('sale',          'разпродажба',    '/seɪl/',          'A2', 'Пазаруване', 'Everything is on sale.',               'Всичко е на разпродажба.'),
('price',         'цена',           '/praɪs/',         'A2', 'Пазаруване', 'What is the price?',                   'Каква е цената?'),
('queue',         'опашка',         '/kjuː/',          'A2', 'Пазаруване', 'There''s a long queue.',               'Има дълга опашка.'),
('cashier',       'касиер',         '/kæˈʃɪər/',      'A2', 'Пазаруване', 'Pay at the cashier.',                  'Плати на касата.'),
('cash',          'пари в брой',    '/kæʃ/',           'A2', 'Пазаруване', 'Do you pay by cash?',                  'Плащаш ли с пари в брой?'),
('credit card',   'кредитна карта', NULL,              'A2', 'Пазаруване', 'Can I pay by credit card?',            'Мога ли да платя с кредитна карта?'),
('refund',        'връщане на пари','/ˈriːfʌnd/',     'A2', 'Пазаруване', 'I''d like a refund.',                  'Искам да върна парите.'),
('size',          'размер',         '/saɪz/',          'A2', 'Пазаруване', 'What size do you wear?',               'Какъв размер носиш?'),
('fitting room',  'съблекалня',     NULL,              'A2', 'Пазаруване', 'Can I use the fitting room?',          'Мога ли да използвам съблекалнята?'),
('supermarket',   'супермаркет',    '/ˈsuːpərmɑːrkɪt/','A2','Пазаруване', 'I shop at the supermarket.',          'Пазарувам от супермаркета.'),
('bargain',       'изгодна сделка', '/ˈbɑːrɡɪn/',     'A2', 'Пазаруване', 'That''s a real bargain!',              'Това е истинска изгода!'),
('spend',         'харча',          '/spend/',         'A2', 'Пазаруване', 'I spent too much money.',              'Похарчих твърде много пари.'),
('shopping list', 'списък за пазар', NULL,             'A2', 'Пазаруване', 'I always write a shopping list.',      'Винаги пиша списък за пазар.'),

-- ── A2 · Взаимоотношения (Relationships) ────────────────────────────────────
('boyfriend',     'гадже (мъж)',    '/ˈbɔɪfrend/',    'A2', 'Взаимоотношения', 'He is my boyfriend.',              'Той е моето гадже.'),
('girlfriend',    'гадже (жена)',   '/ˈɡɜːrlfrend/',  'A2', 'Взаимоотношения', 'She is my girlfriend.',            'Тя е моето гадже.'),
('husband',       'съпруг',         '/ˈhʌzbənd/',     'A2', 'Взаимоотношения', 'My husband is a chef.',            'Съпругът ми е готвач.'),
('wife',          'съпруга',        '/waɪf/',          'A2', 'Взаимоотношения', 'My wife loves travelling.',        'Съпругата ми обича да пътува.'),
('married',       'женен / омъжена','/ˈmærid/',       'A2', 'Взаимоотношения', 'Are you married?',                 'Оженен/Омъжена ли си?'),
('single',        'необвързан',     '/ˈsɪŋɡəl/',      'A2', 'Взаимоотношения', 'She is single.',                   'Тя е свободна.'),
('neighbour',     'съсед',          '/ˈneɪbər/',      'A2', 'Взаимоотношения', 'My neighbour is very nice.',       'Съседът ми е много мил.'),
('couple',        'двойка',         '/ˈkʌpəl/',       'A2', 'Взаимоотношения', 'They are a lovely couple.',        'Те са красива двойка.'),
('guest',         'гост',           '/ɡest/',          'A2', 'Взаимоотношения', 'We have guests tonight.',          'Тази вечер имаме гости.'),
('host',          'домакин',        '/hoʊst/',         'A2', 'Взаимоотношения', 'She is a great host.',             'Тя е страхотен домакин.'),
('friendship',    'приятелство',    '/ˈfrendʃɪp/',    'A2', 'Взаимоотношения', 'Our friendship is strong.',        'Приятелството ни е силно.'),
('get on well',   'разбирам се добре', NULL,          'A2', 'Взаимоотношения', 'We get on well.',                  'Разбираме се добре.'),
('argue',         'карам се',       '/ˈɑːrɡjuː/',     'A2', 'Взаимоотношения', 'We never argue.',                  'Никога не се карем.'),
('support',       'подкрепям',      '/səˈpɔːrt/',     'A2', 'Взаимоотношения', 'She always supports me.',          'Тя винаги ме подкрепя.'),

-- ── A2 · Свободно време (Leisure & Hobbies) ─────────────────────────────────
('hobby',         'хоби',           '/ˈhɒbi/',        'A2', 'Свободно време', 'My hobby is photography.',          'Хобито ми е фотография.'),
('concert',       'концерт',        '/ˈkɒnsərt/',     'A2', 'Свободно време', 'I went to a concert last night.',   'Снощи бях на концерт.'),
('exhibition',    'изложба',        '/ˌeksɪˈbɪʃən/', 'A2', 'Свободно время', 'The exhibition was amazing.',       'Изложбата беше невероятна.'),
('picnic',        'пикник',         '/ˈpɪknɪk/',      'A2', 'Свободно време', 'Let''s have a picnic!',             'Хайде да направим пикник!'),
('camping',       'къмпинг',        '/ˈkæmpɪŋ/',      'A2', 'Свободно время', 'We went camping last summer.',      'Лятото ходихме на къмпинг.'),
('hiking',        'туризъм / преход','/ˈhaɪkɪŋ/',     'A2', 'Свободно время', 'I love hiking in the mountains.',   'Обичам да ходя по планини.'),
('swimming',      'плуване',        '/ˈswɪmɪŋ/',      'A2', 'Свободно время', 'She goes swimming every day.',      'Тя плува всеки ден.'),
('cycling',       'колоездене',     '/ˈsaɪklɪŋ/',     'A2', 'Свободно vrijeme', 'Cycling keeps you fit.',          'Колоезденето те поддържа в форма.'),
('gardening',     'градинарство',   '/ˈɡɑːrdənɪŋ/',  'A2', 'Свободно vrijeme', 'Gardening is relaxing.',          'Градинарството е relaxing.'),
('board game',    'настолна игра',  NULL,              'A2', 'Свободно время', 'We play board games on Fridays.',   'В петък играем настолни игри.'),
('cinema',        'кино',           '/ˈsɪnəmə/',      'A2', 'Свободно время', 'Shall we go to the cinema?',        'Да отидем ли на кино?'),
('festival',      'фестивал',       '/ˈfestɪvəl/',    'A2', 'Свободно время', 'The music festival was great.',     'Музикалният фестивал беше страхотен.'),
('photography',   'фотография',     '/fəˈtɒɡrəfi/',  'A2', 'Свободно время', 'I''m into photography.',            'Занимавам се с фотография.'),
('volunteer',     'доброволец',     '/ˌvɒlənˈtɪər/', 'A2', 'Свободно время', 'She volunteers at a shelter.',      'Тя работи доброволно в приют.'),

-- ── A2 · Ресторант и храна (Restaurant & Food) ──────────────────────────────
('menu',          'меню',           '/ˈmenjuː/',      'A2', 'Ресторант', 'Can I see the menu?',                  'Мога ли да видя менюто?'),
('order',         'поръчвам',       '/ˈɔːrdər/',      'A2', 'Ресторант', 'I''d like to order, please.',          'Искам да поръчам, моля.'),
('starter',       'предястие',      '/ˈstɑːrtər/',    'A2', 'Ресторант', 'I''ll have the soup as a starter.',    'Ще взема супа като предястие.'),
('main course',   'основно ястие',  NULL,              'A2', 'Ресторант', 'What''s the main course?',             'Какво е основното ястие?'),
('dessert',       'десерт',         '/dɪˈzɜːrt/',     'A2', 'Ресторант', 'I''d like a dessert, please.',         'Искам десерт, моля.'),
('bill',          'сметка',         '/bɪl/',           'A2', 'Ресторант', 'Can we have the bill, please?',        'Можем ли да вземем сметката?'),
('tip',           'бакшиш',         '/tɪp/',           'A2', 'Ресторант', 'We left a 10% tip.',                   'Оставихме 10% бакшиш.'),
('vegetarian',    'вегетарианско',  '/ˌvedʒɪˈteəriən/','A2','Ресторант', 'Do you have vegetarian options?',     'Имате ли вегетарианско меню?'),
('takeaway',      'за вкъщи',       '/ˈteɪkəweɪ/',   'A2', 'Ресторант', 'Let''s get a takeaway.',               'Хайде да вземем нещо за вкъщи.'),
('reservation',   'резервация',     '/ˌrezəˈveɪʃən/','A2', 'Ресторант', 'I have a reservation for two.',        'Имам резервация за двама.'),
('waiter',        'сервитьор',      '/ˈweɪtər/',      'A2', 'Ресторант', 'Excuse me, waiter!',                   'Извинете, сервитьорко!'),
('delicious',     'вкусен',         '/dɪˈlɪʃəs/',     'A2', 'Ресторант', 'This is delicious!',                   'Това е вкусно!'),

-- ── A2 · Времеви изрази (Time Expressions) ───────────────────────────────────
('recently',      'наскоро',        '/ˈriːsəntli/',   'A2', 'Времеви изрази', 'I recently moved here.',           'Наскоро се преместих тук.'),
('last year',     'миналата година', NULL,             'A2', 'Времеви изрази', 'Last year I visited France.',      'Миналата година посетих Франция.'),
('next week',     'следващата седмица', NULL,          'A2', 'Времеви изрази', 'I''ll see you next week.',         'Ще те видя следващата седмица.'),
('ago',           'преди',           '/əˈɡoʊ/',        'A2', 'Времеви изрази', 'I met her two years ago.',         'Запознах се с нея преди две години.'),
('in a while',    'след малко',      NULL,             'A2', 'Времеви изрази', 'I''ll be there in a while.',       'Ще съм там след малко.'),
('immediately',   'веднага',         '/ɪˈmiːdiətli/', 'A2', 'Времеви изрази', 'Call me immediately!',             'Обади ми се веднага!'),
('rarely',        'рядко',           '/ˈreərli/',      'A2', 'Времеви изрази', 'I rarely watch TV.',               'Рядко гледам телевизия.'),
('nowadays',      'днес / наши дни', '/ˈnaʊədeɪz/',   'A2', 'Времеви изрази', 'Nowadays everyone uses phones.',   'Днес всеки използва телефони.'),
('once a week',   'веднъж седмично', NULL,             'A2', 'Времеви изрази', 'I exercise once a week.',          'Спортувам веднъж седмично.'),
('in the morning','сутринта',        NULL,             'A2', 'Времеви изрази', 'I study in the morning.',          'Уча сутринта.'),

-- ── B1 · Финанси (Finance & Money) ───────────────────────────────────────────
('budget',        'бюджет',         '/ˈbʌdʒɪt/',      'B1', 'Финанси', 'We need to set a budget.',              'Трябва да определим бюджет.'),
('savings',       'спестявания',    '/ˈseɪvɪŋz/',     'B1', 'Финанси', 'I have some savings in the bank.',      'Имам спестявания в банката.'),
('rent',          'наем',           '/rent/',          'B1', 'Финанси', 'The rent is very high here.',           'Наемът тук е много висок.'),
('mortgage',      'ипотека',        '/ˈmɔːrɡɪdʒ/',   'B1', 'Финанси', 'They took out a mortgage.',             'Те взеха ипотека.'),
('insurance',     'застраховка',    '/ɪnˈʃʊərəns/',  'B1', 'Финанси', 'Do you have travel insurance?',         'Имате ли пътна застраховка?'),
('tax',           'данък',          '/tæks/',          'B1', 'Финанси', 'We all pay tax.',                       'Всички плащаме данъци.'),
('income',        'доход',          '/ˈɪnkʌm/',       'B1', 'Финанси', 'Her income is very good.',              'Доходът й е много добър.'),
('loan',          'заем',           '/loʊn/',          'B1', 'Финанси', 'I took out a loan.',                    'Взех заем.'),
('debt',          'дълг',           '/det/',           'B1', 'Финанси', 'He is in debt.',                        'Той е в дълг.'),
('invest',        'инвестирам',     '/ɪnˈvest/',      'B1', 'Финанси', 'She invests in stocks.',                'Тя инвестира в акции.'),
('afford',        'мога да си позволя','/əˈfɔːrd/',  'B1', 'Финанси', 'I can''t afford a new car.',             'Не мога да си позволя нова кола.'),
('charge',        'начислявам / цена','/tʃɑːrdʒ/',  'B1', 'Финанси', 'They charge extra for delivery.',        'Начисляват допълнително за доставка.'),
('withdraw',      'тегля (пари)',   '/wɪðˈdrɔː/',     'B1', 'Финанси', 'I need to withdraw cash.',              'Трябва да тегля пари.'),
('currency',      'валута',         '/ˈkɜːrənsi/',    'B1', 'Финанси', 'What is the local currency?',           'Каква е местната валута?'),
('exchange rate', 'обменен курс',   NULL,              'B1', 'Финанси', 'Check the exchange rate first.',        'Провери обменния курс първо.'),
('fee',           'такса',          '/fiː/',           'B1', 'Финанси', 'There is a small fee.',                 'Има малка такса.'),
('profit',        'печалба',        '/ˈprɒfɪt/',      'B1', 'Финанси', 'The company made a profit.',            'Компанията реализира печалба.'),
('expense',       'разход',         '/ɪkˈspens/',     'B1', 'Финанси', 'Travel is a big expense.',              'Пътуването е голям разход.'),

-- ── B1 · Спорт (Sport) ────────────────────────────────────────────────────────
('match',         'мач',            '/mætʃ/',          'B1', 'Спорт', 'The match starts at 8.',                 'Мачът започва в 8.'),
('score',         'резултат',       '/skɔːr/',         'B1', 'Спорт', 'What''s the score?',                     'Какъв е резултатът?'),
('training',      'тренировка',     '/ˈtreɪnɪŋ/',     'B1', 'Спорт', 'He goes to training three times a week.','Ходи на тренировка три пъти седмично.'),
('coach',         'треньор',        '/koʊtʃ/',         'B1', 'Спорт', 'Our coach is very demanding.',           'Нашият треньор е много взискателен.'),
('championship',  'първенство',     '/ˈtʃæmpiənʃɪp/', 'B1', 'Спорт', 'They won the championship.',            'Спечелиха първенството.'),
('athlete',       'атлет / спортист','/ˈæθliːt/',     'B1', 'Спорт', 'She is a professional athlete.',         'Тя е професионален атлет.'),
('stadium',       'стадион',        '/ˈsteɪdiəm/',    'B1', 'Спорт', 'The stadium holds 50,000 people.',       'Стадионът побира 50 000 души.'),
('referee',       'съдия',          '/ˌrefəˈriː/',    'B1', 'Спорт', 'The referee made a bad decision.',       'Съдията взе лошо решение.'),
('trophy',        'трофей',         '/ˈtroʊfi/',       'B1', 'Спорт', 'They lifted the trophy.',                'Вдигнаха трофея.'),
('fitness',       'фитнес / форма', '/ˈfɪtnəs/',      'B1', 'Спорт', 'Running improves your fitness.',         'Бягането подобрява физическата форма.'),
('tournament',    'турнир',         '/ˈtɜːrnəmənt/',  'B1', 'Спорт', 'He entered the tournament.',             'Той се записа в турнира.'),
('defeat',        'поражение',      '/dɪˈfiːt/',      'B1', 'Спорт', 'They suffered a heavy defeat.',          'Претърпяха тежко поражение.'),
('victory',       'победа',         '/ˈvɪktəri/',     'B1', 'Спорт', 'The victory was unexpected.',            'Победата беше неочаквана.'),
('opponent',      'противник',      '/əˈpoʊnənt/',    'B1', 'Спорт', 'The opponent was very strong.',          'Противникът беше много силен.'),
('captain',       'капитан',        '/ˈkæptɪn/',      'B1', 'Спорт', 'She is the team captain.',               'Тя е капитан на отбора.'),
('penalty',       'наказание / дузпа','/ˈpenəlti/',  'B1', 'Спорт', 'He scored from the penalty.',            'Вкара от дузпа.'),

-- ── B1 · Екология (Environment) ──────────────────────────────────────────────
('pollution',     'замърсяване',    '/pəˈluːʃən/',    'B1', 'Екология', 'Air pollution is a serious problem.',  'Замърсяването на въздуха е сериозен проблем.'),
('recycling',     'рециклиране',    '/rɪˈsaɪklɪŋ/',  'B1', 'Екология', 'Recycling helps the environment.',     'Рециклирането помага на природата.'),
('renewable',     'възобновяем',    '/rɪˈnjuːəbəl/', 'B1', 'Екология', 'Solar is a renewable energy source.',  'Слънчевата е възобновяем енергиен източник.'),
('climate change','климатични промени', NULL,         'B1', 'Екология', 'Climate change is a global threat.',   'Климатичните промени са глобална заплаха.'),
('carbon footprint','въглероден отпечатък', NULL,     'B1', 'Екология', 'Reduce your carbon footprint.',       'Намали въглеродния си отпечатък.'),
('deforestation', 'обезлесяване',   '/ˌdiːfɒrɪˈsteɪʃən/','B1','Екология','Deforestation destroys habitats.',  'Обезлесяването унищожава местообитания.'),
('endangered',    'застрашен (вид)','/ɪnˈdeɪndʒərd/','B1', 'Екология', 'Pandas are endangered.',               'Пандите са застрашен вид.'),
('ecosystem',     'екосистема',     '/ˈiːkoʊsɪstəm/', 'B1','Екология', 'Protect the ocean ecosystem.',         'Защити океанската екосистема.'),
('habitat',       'местообитание',  '/ˈhæbɪtæt/',    'B1', 'Екология', 'Forests are a natural habitat.',       'Горите са естествено местообитание.'),
('fossil fuel',   'изкопаеми горива', NULL,           'B1', 'Екология', 'We must reduce fossil fuel use.',      'Трябва да намалим употребата на изкопаеми горива.'),
('solar panel',   'соларен панел',  NULL,             'B1', 'Екология', 'They installed solar panels.',         'Поставиха соларни панели.'),
('waste',         'отпадъци',       '/weɪst/',        'B1', 'Екология', 'Reduce food waste.',                   'Намали хранителните отпадъци.'),
('organic',       'органичен',      '/ɔːrˈɡænɪk/',   'B1', 'Екология', 'I buy organic vegetables.',            'Купувам органични зеленчуци.'),
('biodiversity',  'биоразнообразие', NULL,            'B1', 'Екология', 'Biodiversity is under threat.',        'Биоразнообразието е застрашено.'),
('flood',         'наводнение',     '/flʌd/',         'B1', 'Екология', 'The flood destroyed many homes.',      'Наводнението унищожи много домове.'),
('drought',       'суша',           '/draʊt/',        'B1', 'Екология', 'A long drought hit the region.',       'Продължителна суша удари региона.'),

-- ── B1 · Технологии — основи (Technology Basics) ────────────────────────────
('app',           'приложение',     '/æp/',            'B1', 'Технологии', 'Download the app.',                  'Изтегли приложението.'),
('screen',        'екран',          '/skriːn/',        'B1', 'Технологии', 'The screen is cracked.',             'Екранът е пукнат.'),
('keyboard',      'клавиатура',     '/ˈkiːbɔːrd/',    'B1', 'Технологии', 'She types fast on her keyboard.',    'Тя пише бързо на клавиатурата.'),
('charger',       'зарядно',        '/ˈtʃɑːrdʒər/',  'B1', 'Технологии', 'Have you seen my charger?',           'Видял ли си зарядното ми?'),
('battery',       'батерия',        '/ˈbætəri/',      'B1', 'Технологии', 'My battery is almost dead.',         'Батерията ми почти е изтощена.'),
('wireless',      'безжичен',       '/ˈwaɪərləs/',    'B1', 'Технологии', 'We have wireless internet.',         'Имаме безжичен интернет.'),
('storage',       'памет / съхранение','/ˈstɔːrɪdʒ/', 'B1','Технологии', 'The phone has 128GB of storage.',    'Телефонът има 128 GB памет.'),
('notification',  'известие',       '/ˌnoʊtɪfɪˈkeɪʃən/','B1','Технологии','Turn off notifications.',           'Изключи известията.'),
('settings',      'настройки',      '/ˈsetɪŋz/',      'B1', 'Технологии', 'Go to settings.',                    'Отиди в настройките.'),
('back up',       'правя резервно копие', NULL,        'B1', 'Технологии', 'Back up your data.',                 'Направи резервно копие на данните.'),
('log in',        'влизам / логвам се', NULL,         'B1', 'Технологии', 'Log in with your email.',            'Влез с имейла си.'),
('crash',         'срива се',       '/kræʃ/',         'B1', 'Технологии', 'The app crashed.',                   'Приложението се срина.'),
('update',        'обновявам',      '/ˈʌpdeɪt/',      'B1', 'Технологии', 'Update your software.',              'Обнови софтуера си.'),
('search engine', 'търсачка',       NULL,              'B1', 'Технологии', 'Use a search engine.',               'Използвай търсачка.'),
('browser',       'браузър',        '/ˈbraʊzər/',     'B1', 'Технологии', 'Which browser do you use?',           'Кой браузър използваш?'),

-- ── B2 · Медии и новини (Media & News) ───────────────────────────────────────
('headline',      'заглавие (новина)','/ˈhedlaɪn/',   'B2', 'Медии', 'The headline shocked everyone.',          'Заглавието шокира всички.'),
('journalist',    'журналист',      '/ˈdʒɜːrnəlɪst/','B2', 'Медии', 'She is an investigative journalist.',     'Тя е разследващ журналист.'),
('broadcast',     'излъчвам',       '/ˈbrɔːdkæst/',  'B2', 'Медии', 'The event was broadcast live.',           'Събитието беше предавано на живо.'),
('editorial',     'редакционен',    '/ˌedɪˈtɔːriəl/','B2', 'Медии', 'He wrote an editorial.',                  'Той написа редакционна статия.'),
('bias',          'пристрастие',    '/ˈbaɪəs/',       'B2', 'Медии', 'Media bias is a concern.',                'Медийната предубеденост е притеснителна.'),
('censorship',    'цензура',        '/ˈsensəʃɪp/',   'B2', 'Медии', 'Censorship limits free speech.',          'Цензурата ограничава свободата на словото.'),
('propaganda',    'пропаганда',     '/ˌprɒpəˈɡændə/','B2','Медии', 'Propaganda can mislead people.',          'Пропагандата може да подвежда хората.'),
('controversy',   'противоречие',   '/ˈkɒntrəvɜːrsi/','B2','Медии','The decision caused controversy.',        'Решението предизвика противоречия.'),
('investigation', 'разследване',    '/ɪnˌvestɪˈɡeɪʃən/','B2','Медии','A full investigation was launched.',   'Започна пълно разследване.'),
('documentary',   'документален',   '/ˌdɒkjəˈmentəri/','B2','Медии','I watched a great documentary.',          'Гледах страхотен документален филм.'),
('circulation',   'тираж',          '/ˌsɜːrkjəˈleɪʃən/','B2','Медии','The newspaper has a large circulation.','Вестникът има голям тираж.'),
('eyewitness',    'очевидец',       '/ˈaɪwɪtnəs/',   'B2', 'Медии', 'An eyewitness spoke to reporters.',      'Очевидец говори с репортери.'),
('anonymous',     'анонимен',       '/əˈnɒnɪməs/',   'B2', 'Медии', 'The source was anonymous.',              'Изворът беше анонимен.'),

-- ── B2 · Описание и характеристики (Describing) ──────────────────────────────
('resourceful',   'находчив',       '/rɪˈsɔːrsfl/',  'B2', 'Характер', 'She is very resourceful.',             'Тя е много находчива.'),
('assertive',     'настоятелен',    '/əˈsɜːrtɪv/',   'B2', 'Характер', 'Be more assertive in meetings.',       'Бъди по-настоятелен на срещите.'),
('diplomatic',    'дипломатичен',   '/ˌdɪpləˈmætɪk/','B2','Характер', 'She is very diplomatic.',               'Тя е много дипломатична.'),
('cynical',       'цинична',        '/ˈsɪnɪkəl/',    'B2', 'Характер', 'He has a cynical view of politics.',   'Той има циничен поглед върху политиката.'),
('empathetic',    'съчувствен',     '/ˌempəˈθetɪk/', 'B2', 'Характер', 'A good doctor must be empathetic.',    'Добрият лекар трябва да е съчувствен.'),
('conscientious', 'добросъвестен',  '/ˌkɒnʃiˈenʃəs/','B2','Характер', 'She is a conscientious worker.',       'Тя е добросъвестен служител.'),
('introverted',   'интровертен',    '/ˈɪntrəvɜːrtɪd/','B2','Характер','He is quite introverted.',              'Той е доста интровертен.'),
('extroverted',   'екстровертен',   '/ˈekstrəvɜːrtɪd/','B2','Характер','She is very extroverted.',             'Тя е много екстровертна.'),
('naive',         'наивен',         '/naɪˈiːv/',      'B2', 'Характер', 'Don''t be so naive.',                  'Не бъди толкова наивен.'),
('considerate',   'внимателен към другите','/kənˈsɪdərɪt/','B2','Характер','He is always considerate.',        'Той е винаги внимателен към другите.');
